repository: https://github.com/untreu2/nostr-nip19
name: nostr_nip19
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
    sdk: ^3.7.2

dependencies:
    bech32: ^0.2.2

dev_dependencies:
    lints: ^5.0.0
    test: ^1.24.0
