repository: https://github.com/untreu2/nostr-nip19
name: nostr_nip19
description: A Dart library for encoding and decoding Nostr keys and identifiers (npub, nsec, note, nprofile, nevent) using the NIP-19 Bech32 format.
version: 0.1.0

environment:
    sdk: ^3.7.2

dependencies:
    bech32: ^0.2.2

dev_dependencies:
    lints: ^5.0.0
    test: ^1.24.0
